### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by AhmedThahir** [AhmedThahir/Uni_Notes#11]
For now, I've shortened the domain from ahmed-thahir-notes.netlify.app to [uni-notes.netlify.app](https://uni-notes.netlify.app) which is fine, but it would be better to get a nicer domain.

Freenom (where I usually get free domains) is displaying the following error:

> IMPORTANT NOTICE: Because of technical issues the Freenom application for new registrations is temporarily out-of-order.
Please accept our apologies for the inconvenience. We are working on a solution and hope to resume operations shortly.
Thank you for your understanding.

**Comment by Fir121** [comment]
Freenom is in legal trouble with meta, they have not clarified if or when they will return, for now I don't know of any other free domain options, even so I recommend using a paid but cheap option it will be more secure as well as you will have full control (freenom can seize freenom domains if they want and there are cases where they have done so in sites that get high traffic)

You may even be able to get a .com which is more professional.

**Comment by AhmedThahir** [comment]
Oh alright I didn't know about the legal issue. Fair enough.
