### ISSUE TITLE
Hosting on github pages directly

### ISSUE THREAD

**Issue by AhmedThahir** [AhmedThahir/Uni_Notes#14]
I'm currently using Netlify's build tools. I didn't get how to use GitHub Pages directly.

**Comment by Fir121** [comment]
I will make a PR for this, and explain the steps along with it

**Comment by Fir121** [comment]
Before I proceed, if the site is hosted on gh pages the domain will be -> https://AhmedThahir.github.io/Uni_Notes

Unless of course you buy a domain, if that's ok, I'll send a PR with the needed files to deploy directly.

**Comment by Fir121** [comment]
You always have the option to setup a redirect with Netlify to this page in order to retain your current domain name.

**Comment by AhmedThahir** [comment]
your ci.yml runs, but the github pages action keeps failing

**Comment by Fir121** [comment]
Ensure that your `SETTINGS>PAGES` looks like this

![image](https://user-images.githubusercontent.com/62911996/227371744-897ae9b1-153c-4ed8-bea6-ee760f7e36c7.png)

**Comment by AhmedThahir** [comment]
It worked, but what is the benefit of using github pages directly?

I am not able to notice any visible difference in speed between
- uni-notes.netlify.app
- ahmedthahir.github.io/Uni_Notes

**Comment by Fir121** [comment]
That is up to you, personally they are both great for different use cases, but at a small scale GitHub pages seems faster, at least on my end, maybe test it using some online tools or a good ol' stopwatch😅

In the end, use whichever you prefer the most, Netlify also comes with more features than GitHub pages but whether you need those for this project or not is a different discussion.

**Comment by AhmedThahir** [comment]
Both have very similar speed results (**Netlify is actually better**).

## GitHub pages

![Screen Shot 2023-03-25 at 5 02 26 PM](https://user-images.githubusercontent.com/94914628/227718760-a220a0b3-10fa-418c-ad68-9df490cb311a.png)

## Netlify

![Screen Shot 2023-03-25 at 5 03 54 PM](https://user-images.githubusercontent.com/94914628/227718821-93f5a4c7-5085-4ba9-a6d1-44b35cbe9450.png)
