### ISSUE TITLE
Contributors Badge not updated

### ISSUE THREAD

**Issue by AhmedThahir** [AhmedThahir/Uni_Notes#26]
Anyone has an idea why this is not updating? Sivaa is not coming up. It has been a few hours since his contribution.

https://contrib.rocks/image?repo=AhmedThahir/Uni_Notes

**Comment by Fir121** [comment]
Seems to be a caching issue, might show up in some time. Meanwhile it works on the staging web app [stg.contrib.rocks](https://stg.contrib.rocks/image?repo=AhmedThahir/Uni_Notes)

See ![](https://stg.contrib.rocks/image?repo=AhmedThahir/Uni_Notes)

**Comment by AhmedThahir** [comment]
How's the staging web app different?

**Comment by Fir121** [comment]
It just hasn't cached a result yet I assume
