### ISSUE TITLE
Biotechnology Notes

### ISSUE THREAD

**Issue by Gurusshitha** [AhmedThahir/Uni_Notes#37]
Hi Guys! I will be uploading my biotech notes! Hope it helps!
I discussed this with Thahir.

**Comment by AhmedThahir** [comment]
This is a good addition. Hope more courses are added.

Kindly ensure you contributions are in alignment with the contribution guidelines (which are being made). You can check its status [here](https://github.com/AhmedThahir/Uni_Notes/issues/32)
